# -*- coding: utf-8 -*-
"""A Text-Based Python Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12wgZROdfZsGamr2sb1UM1O98XsC13O8F
"""

# Define the rooms and their descriptions
rooms = {
    'hall': {
        'description': 'You are in a grand hall. There are doors to the north and east.',
        'north': 'kitchen',
        'east': 'dining room',
        'item': 'key'
    },
    'kitchen': {
        'description': 'You are in a kitchen. There is a door to the south.',
        'south': 'hall'
    },
    'dining room': {
        'description': 'You are in a dining room. There is a door to the west.',
        'west': 'hall',
        'item': 'potion'
    }
}

# Initialize the player's current room and inventory
current_room = 'hall'
inventory = []

# Function to describe the current room
def describe_room(room):
    print(rooms[room]['description'])
    if 'item' in rooms[room]:
        print(f'You see a {rooms[room]["item"]} here.')

# Function to move to a new room
def move(direction):
    global current_room
    if direction in rooms[current_room]:
        current_room = rooms[current_room][direction]
        describe_room(current_room)
    else:
        print('You can\'t go that way.')

# Function to pick up an item
def pick_up(item):
    global current_room
    if 'item' in rooms[current_room] and rooms[current_room]['item'] == item:
        inventory.append(item)
        del rooms[current_room]['item']
        print(f'You picked up the {item}.')
    else:
        print(f'There is no {item} here.')

# Main game loop
def game():
    print('Welcome to the Enhanced Adventure Game!')
    describe_room(current_room)
    while True:
        command = input('> ').split()
        if len(command) == 1:
            if command[0] in ['north', 'south', 'east', 'west']:
                move(command[0])
            elif command[0] == 'quit':
                print('Thanks for playing!')
                break
            else:
                print('Invalid command. Try "north", "south", "east", "west", or "quit".')
        elif len(command) == 2 and command[0] == 'pick':
            pick_up(command[1])
        else:
            print('Invalid command.')

# Run the game
game()